#!/bin/bash -ex
set -o pipefail

base="$(dirname "$0")"

trap 'kill $(jobs -p); wait' EXIT

docker run --name denorm-example-init --init --rm -p 5432:5432 -e POSTGRES_PASSWORD=password postgres:12 &

sleep 1

until docker exec denorm-example-init pg_isready -U postgres > /dev/null 2> /dev/null; do
  sleep 0.2
done

export PGHOST=localhost
export PGUSER=postgres
export PGPASSWORD=password

psql -1 -f "$base/schema.sql" -v ON_ERROR_STOP=true
denorm create_sql "$base/book_full.yml"
denorm create_sql "$base/book_full.yml" | psql -1 -f - -v ON_ERROR_STOP=true

psql -1 -f "$base/data.sql" -v ON_ERROR_STOP=true

echo 'Access PostgreSQL at localhost:5432'

wait
